apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
  labels:
    cluster: c0
    app: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luckhass/training-model.git
    targetRevision: HEAD
    path: argo/cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
