apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo
  labels:
    app: minio
spec:
  project: default
  source:
    repoURL: https://github.com/luckhass/training-model.git
    targetRevision: HEAD
    path: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
